# NVIDIA sysctl defaults for DGX systems
# From nvidia-kernel-defaults 21.05-1

# Use best local address for ARP requests
net.ipv4.conf.all.arp_announce = 2
net.ipv4.conf.default.arp_announce = 2

# Only reply to ARP on the interface with the target address
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.default.arp_ignore = 1
